name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  webhook-url:
    description: 'Webhook URL'
    required: true
  provider:
    description: 'Provider: slack or msteams'
    required: true
    default: 'slack'
  channel:
    description: 'Channel name'
    required: false
    default: '#general'
  github-provider-map:
    description: 'Map GitHub username to Slack user IDs. Eg: "DavideViolante:UABCDEFGH,foobar123:UIHJKLMNO"'
    required: false
    default: false
  ignore-label:
    description: 'Ignore Pull Requests with that label'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'