name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  webhook-url:
    description: 'Webhook URL'
    required: true
  channel:
    description: 'Channel name'
    required: false
    default: '#general'
  github-provider-map:
    description: 'Map GitHub username to Slack/Teams user IDs. Eg: "DavideViolante:UABCDEFGH,foobar123:UIHJKLMNO"'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'